<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35164" started-at="2018-10-16T10:19:35Z" finished-at="2018-10-16T10:20:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35164" started-at="2018-10-16T10:19:35Z" finished-at="2018-10-16T10:20:11Z">
      <class name="LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:LoginTest@5b275dab]" name="setUp" is-config="true" duration-ms="14242" started-at="2018-10-16T15:49:35Z" finished-at="2018-10-16T15:49:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="doLogin()[pri:1, instance:LoginTest@5b275dab]" name="doLogin" duration-ms="3199" started-at="2018-10-16T15:49:50Z" finished-at="2018-10-16T15:49:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="shutDown()[pri:0, instance:LoginTest@5b275dab]" name="shutDown" is-config="true" duration-ms="2637" started-at="2018-10-16T15:49:53Z" finished-at="2018-10-16T15:49:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:LoginTest@5b275dab]" name="setUp" is-config="true" duration-ms="11662" started-at="2018-10-16T15:49:56Z" finished-at="2018-10-16T15:50:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkTitle()[pri:2, instance:LoginTest@5b275dab]" name="checkTitle" duration-ms="28" started-at="2018-10-16T15:50:07Z" finished-at="2018-10-16T15:50:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [dddgdg] but found [AdminLTE 2 | Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [dddgdg] but found [AdminLTE 2 | Log in]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at LoginTest.checkTitle(LoginTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTitle -->
        <test-method status="PASS" signature="shutDown()[pri:0, instance:LoginTest@5b275dab]" name="shutDown" is-config="true" duration-ms="3328" started-at="2018-10-16T15:50:07Z" finished-at="2018-10-16T15:50:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDown -->
      </class> <!-- LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
